name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Lint
        run: npm run lint
        if: ${{ ! startsWith(matrix.node-version, '16.') }}

      - name: Test
        run: npm test
        if: ${{ false }} # Disable testing for now

  package:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Build WASM
        run: cd server && npm run build-wasm && cd ..

      - name: Package Extension
        run: npx vsce package

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scrapscript-lsp-extension
          path: "*.vsix"
